name: CI

on: [push]


jobs:
  
  security:
    name: security
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Bandit Scan
      uses: shundor/python-bandit-scan@v1.0
      with: 
        path: "./src/app.py"
        level: UNDEFINED
        confidence: UNDEFINED
        excluded_paths: "*.txt"
        exit_zero: true
    - name: validation
      run: source ./test.sh
    - name: Docker meta
      if: env.flag == false
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          alanbasurto/apifgh
        tags: |
          type=semver,pattern={{major}}.{{minor}}
    - name: Set up QEMU
      if: env.flag == flase
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      if: env.flag == false
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: env.flag == false
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push with flag
      if: env.flag == false
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
