name: CI

on: [push]

jobs:
  
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello world
    - name: Run a multi-line script
      run: |
        echo add other actions
        echo test and deploy your project
    - name: Bandit Scan
      uses: shundor/python-bandit-scan@v1.0
      with: 
        path: "./src/app.py"
        level: UNDEFINED
        confidence: UNDEFINED
        excluded_paths: "*.txt"
        exit_zero: true       
