name: CI

on: [push]

jobs:
  
  security:
    name: security
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Bandit Scan
      uses: shundor/python-bandit-scan@v1.0
      with: 
        path: "./src/app.py"
        level: UNDEFINED
        confidence: UNDEFINED
        excluded_paths: "*.txt"
        exit_zero: true
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: results.sarif
    - name: validation
      run: source ./test.sh


      
